export const ufroVolleyConfig = {
  canvas: {
    width: 1920,
    height: 1080,
  },
  match: {
    pointsToWin: 5,
    pointFreezeMs: 1100,
    serveDelayMs: 3000,
    resultDelayMs: 1400,
  },
  intro: {
    controlsAutoHideMs: 0,
  },
  physics: {
    fixedStep: 1 / 60,
    maxFrameTime: 0.1,
    maxSubsteps: 6,
    gravity: { x: 0, y: 2400 },
    airDrag: 0.002,
    groundFriction: 0.82,
  },
  ball: {
    radius: 44,
    mass: 0.92,
    restitution: 0.9,
    linearDamping: 0.003,
    spawnY: 165,
    maxSpeed: 1800,
    wallRestitution: 0.92,
    serveSpawnJitterX: 96,
    serveSpawnJitterY: 34,
    serveVelocityJitterX: 95,
    serveVelocityJitterY: 48,
  },
  net: {
    x: 960,
    y: 554,
    width: 42,
    height: 320,
    restitution: 0.38,
  },
  handTracking: {
    detectIntervalMs: 100,
    persistenceMs: 170,
    scoreThreshold: 0.88,
    releaseThreshold: 0.5,
    triggerCooldownMs: 460,
    videoWidth: 320,
    videoHeight: 240,
  },
  players: {
    width: 136,
    height: 224,
    colliderRadius: 62,
    mass: 1.75,
    restitution: 0.34,
    linearDamping: 0.015,
    angularDamping: 0.026,
    jumpCooldownMs: 760,
    jumpImpulseY: -1180,
    jumpImpulseFrontX: 145,
    jumpImpulseBackX: 106,
    maxTilt: 1.24,
    jumpImpulseVarianceY: 92,
    jumpImpulseVarianceX: 36,
    jumpAngularVariance: 0.8,
    groundAngularBounce: 0.012,
    ballAngularImpactBoost: 0.8,
  },
  wobble: {
    frontTorqueAmplitude: 14.2,
    backTorqueAmplitude: 11.8,
    frontTorqueFrequency: 2.8,
    backTorqueFrequency: 2.25,
    frontMicroImpulse: 138,
    backMicroImpulse: 116,
    microImpulseFrequency: 2.3,
  },
  formation: {
    leftBoundary: 150,
    rightBoundary: 1770,
    midlinePadding: 86,
    slotLeashStrength: 1.1,
    slotLeashDamping: 0.96,
    leashDeadZone: 170,
    minGapWithinTeam: 180,
    left: {
      frontBaseX: 680,
      backBaseX: 430,
    },
    right: {
      frontBaseX: 1240,
      backBaseX: 1490,
    },
  },
  controls: {
    leftJumpKey: "KeyF",
    rightJumpKey: "KeyJ",
    confirmKey: "Enter",
    backKey: "Escape",
    navPrev: ["KeyA", "KeyW", "ArrowLeft", "ArrowUp"],
    navNext: ["KeyD", "KeyS", "ArrowRight", "ArrowDown"],
  },
  render: {
    titlePalette: {
      shadow: "#5a2f1a",
      edge: "#8d5424",
      fill: "#ffd65a",
      glow: "rgba(255, 243, 186, 0.85)",
    },
    teams: {
      left: {
        label: "GATOS",
        color: "#ffd44f",
        dark: "#63381f",
      },
      right: {
        label: "PERROS",
        color: "#98d7ff",
        dark: "#284860",
      },
    },
    shadows: {
      ballMinScale: 0.35,
      ballMaxScale: 1,
      alphaMin: 0.18,
      alphaMax: 0.62,
    },
    netPost: {
      width: 118,
      height: 598,
      topY: 228,
      extensionWidth: 52,
      extensionColor: "#ececec",
    },
    spriteProfiles: {
      "cat-gray": {
        scale: 0.62,
        offsets: [
          { x: 0, y: -12 },
          { x: 6, y: -10 },
          { x: 6, y: -8 },
          { x: 8, y: -4 },
          { x: 10, y: -2 },
        ],
      },
      "cat-yellow": {
        scale: 0.62,
        offsets: [
          { x: 0, y: -12 },
          { x: 4, y: -10 },
          { x: 6, y: -8 },
          { x: 8, y: -4 },
          { x: 10, y: -2 },
        ],
      },
      "dog-white": {
        scale: 0.62,
        offsets: [
          { x: 0, y: -14 },
          { x: 4, y: -10 },
          { x: 6, y: -8 },
          { x: 8, y: -2 },
          { x: 10, y: 2 },
        ],
      },
      "dog-brown": {
        scale: 0.62,
        offsets: [
          { x: 0, y: -14 },
          { x: 4, y: -10 },
          { x: 6, y: -8 },
          { x: 8, y: -2 },
          { x: 10, y: 2 },
        ],
      },
    },
  },
};
