export const ufroBasketConfig = {
  canvas: {
    width: 1280,
    height: 720,
  },
  model: {
    path: "https://teachablemachine.withgoogle.com/models/QcFNjF-nf/model.json",
    metadataPath: "https://teachablemachine.withgoogle.com/models/QcFNjF-nf/metadata.json",
    classifyIntervalMs: 90,
  },
  input: {
    fistLabels: ["puño cerrado", "puno cerrado"],
    openLabels: ["mano abierta"],
    backgroundLabels: ["fondo"],
    holdThreshold: 0.38,
    releaseThreshold: 0.68,
    neutralThreshold: 0.26,
    releaseCooldownMs: 220,
    fistPersistenceFrames: 2,
    openPersistenceFrames: 1,
  },
  debug: {
    showHoopOverlay: false,
  },
  physics: {
    fixedStep: 1 / 60,
    maxFrameTime: 0.1,
    maxSubsteps: 6,
    gravity: 1700,
    airDrag: 0.0015,
    floorY: 632,
    rimRestitution: 0.82,
    boardRestitution: 0.74,
    groundRestitution: 0.42,
  },
  controls: {
    chargeKey: "Space",
    confirmKey: "Enter",
    backKey: "Escape",
    navPrev: ["KeyA", "KeyW", "ArrowLeft", "ArrowUp"],
    navNext: ["KeyD", "KeyS", "ArrowRight", "ArrowDown"],
  },
  player: {
    floorX: 250,
    floorY: 632,
    scale: 0.48,
    releasePoseMs: 220,
  },
  ball: {
    radius: 26,
    resetDelayMs: 780,
    perfectCharge: 50,
    perfectWindow: 2,
    shortThreshold: 45,
    longThreshold: 56,
    chargeSpeed: 92,
    chargeMin: 0,
    chargeMax: 100,
  },
  shot: {
    targetX: 922,
    targetY: 462,
    idealFlightTime: 0.82,
    errorVelocityFactorX: 0.013,
    errorVelocityFactorY: 0.01,
    errorVerticalBias: 6.4,
  },
  hoop: {
    rimLeftX: 840,
    rimTopY: 458,
    rimScale: 0.42,
    rimThicknessScale: 0.42,
    edgeWidthScale: 0.1,
    scoreSensorYOffset: 18,
    scoreSensorPadding: 12,
    netOffsetX: 6,
    netOffsetY: 10,
    netScale: 0.39,
    connectorOffsetX: -6,
    connectorOffsetY: -6,
    connectorScale: 0.42,
    postOffsetX: 44,
    postOffsetY: 0,
    postScale: 0.39,
    tripodOffsetX: 14,
    tripodOffsetY: -8,
    tripodScale: 0.39,
  },
  render: {
    poseAnchors: {
      idle: { x: 0.74, y: 0.40 },
      charge: { x: 0.78, y: 0.315 },
      release: { x: 0.80, y: 0.235 },
    },
    powerBar: {
      x: 318,
      y: 642,
      width: 644,
      height: 24,
    },
  },
};
